seed: 123
device: 'cuda'
num_workers: 1

env_name: button-press-v2
camera_name: d
obs_type: features
num_demos: 2
context_num: 3
include_timestep: True

reward_fn: coverage
tau: 1
ent_reg: .01
sdtw_smoothing: 5
mask_k: 10
niter: 100

discount_factor: .9
expl_noise: .4
min_expl_noise: 0.0

n_eval_episodes: 10

eval_period: 10000
model_period: 100000
video_period: 400

wandb_project: TemporalOT
wandb_mode: online
wandb_tags: []

defaults:
  - _self_

hydra:
  run:
    dir: ./train_logs/${now:%Y-%m-%d-%H-%M-%S-%f}_envt=${env_name}_rm=${reward_fn}_${uuid:}
